version: "3.9"
services:

  backend:
    image: ath31st/trae_back
    container_name: trae_back
    ports:
      - "8088:8088"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    depends_on:
      - postgres-backend

  postgres-backend:
    image: postgres:15.2
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: traeDB
    volumes:
      - "database:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d traeDB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure

volumes:
  database:

networks:
  trae-net:
    name: trae-net
    driver: bridge
