version: "3.9"
services:

  backend:
    image: ath31st/trae_back
    container_name: trae_back
    ports:
      - "8088:8088"
    depends_on:
      - postgres-backend

  postgres-backend:
    image: postgres:15.2
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: traeDB
    restart: on-failure