version: "3.9"
services:
  postgres:
    image: postgres:15.0
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: traeDB
    restart: on-failure