version: "3.9"
services:

  backend:
    image: ath31st/trae_back
    container_name: trae_back
    ports:
      - "8088:8088"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "POSTGRES_URL=${PG_URL}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASS=${PG_PASSWORD}"
    networks:
      - trae-net
    depends_on:
      - postgres-backend

  postgres-backend:
    image: postgres:15.2
    container_name: postgres_db
    ports:
      - "${PG_PORT}:${PG_PORT}"
    command: -p ${PG_PORT}
    environment:
      PGUSER: "${PG_USER}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DB}"
    volumes:
      - "database:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure
    networks:
        - trae-net

volumes:
  database:

networks:
  trae-net:
    name: trae-net
    driver: bridge
