spring:
  liquibase:
    enabled: false
    change-log: classpath:./db/changelog/db.changelog-master.xml

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/traeDB}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASS:postgres}
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create

#  logging:
#    level:
#      org:
#        springframework:
#          security: off