server:
  port: 8088

scheduler:
  # sec(0-59) min(0-59) hour(0-23) day(1-31) month(1-12) day of week(1-7)
  start-day: "0 0 7 * * *"
  end-day: "0 0 23 * * *"

jwt:
  access:
    secret: VERY_SECRET_PHRASE_OOOF
    duration: 50 # minutes
  refresh:
    secret: VERY_SECRET_PHRASE_FOR_REFRESH_TOKEN_OOOF
    duration: 30 # days




