spring:
  liquibase:
    enabled: false

  datasource:
    url: jdbc:postgresql://postgres_db:5432/traeDB
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create