spring:
  liquibase:
    enabled: false
    change-log: classpath:./db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:postgresql://localhost:5444/devTraeDB
    username: trae_dev
    password: dev
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      springframework:
        security: debug