server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/traeDB
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create

#  logging:
#    level:
#      org:
#        springframework:
#          security: off