server:
  port: 8088

scheduler:
  # sec(0-59) min(0-59) hour(0-23) day(1-31) month(1-12) day of week(1-7)
  start-day: "0 0 8 * * *"
  end-day: "0 0 19 * * *"

spring:
  liquibase:
    enabled: false

  datasource:
    #url: jdbc:postgresql://localhost:5432/traeDB
    url: jdbc:postgresql://postgres_db:5432/traeDB
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create

#  logging:
#    level:
#      org:
#        springframework:
#          security: off